---
# ansible-playbook windows/win-shutdown.yaml --ask-vault-pass -l test
- hosts: all
  vars_files:
    'win-passwords.yaml'
  tasks:
  
  - name: Shutdown Windows PC
    ansible.windows.win_command:
      cmd: shutdown -s -f -t 0
...